### ISSUE TITLE
The latest Selenium containers are failing on VIC

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#2126]
##### For bug reports, please include the information below:

Please fill out both the Basic Information and Detailed Information sections.

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version:
- Embedded or external PSC:
- Filename of the OVA you deployed:
1.4.3 GA

- How was the OVA deployed? (Flex client, HTML5 client, ovftool):
- Does the VIC appliance recieve configuration by DHCP?
- What stage of the Appliance Lifecycle is the VIC appliance in?
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
  Note: The support bundle may contain private information. If you are not comfortable with posting this publicly, please contact VMware GSS.

OPTIONAL, but helpful:

- IP address of VIC appliance:
- Hostname of VIC appliance:
- IP address of vCenter Server:
- Hostname of vCenter Server:

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
Containers come up fine but docker logs show there are errors and the hub container was not able to start sucessfully

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle

- Provide additional detail as necessary:

Docker-compose File:

```
version: '2.2'
services:
  hub:
    image: "selenium/hub"
    ports:
      - "4444:4444"
  chrome:
    cpu_count: 1
    image: "selenium/node-chrome"
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_X_SESSION=3 
      - GRID_MAX_SESSION=10
    links:
      - "hub"
    expose:
      - "5555"
  firefox:
    cpu_count: 1
    image: "selenium/node-firefox"
    environment:
      - HOME=/home/seluser
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_X_SESSION=3 
      - GRID_MAX_SESSION=10
    links:
      - "hub"
    expose:
      - "5555"
```

----------
If the 3.13(previous) container image is used, then it runs as expected but the latest image is failing. It does however run successfully on native docker. So investigation needs to be done to identify what changed between the releases.

##### For feature requests/user stories, please include the information below:

**User Statement:**

**Details:**

**Acceptance Criteria:**
