### ISSUE TITLE
Comments in example config.yaml

### ISSUE THREAD

**Issue by ali5ter** [vmware/vic-product#374]
To aid the users understanding of the example config.yaml, comments can be added to describe the key-value pairs. 

This has been a problem for users of the vSphere Appliance deployment and upgrade CLI who are trying to edit the JSON config files. Since we're using YAML, we have the opportunity to make something better.

**Comment by casualjim** [comment]
here's an example of the config without the comments

```yaml
name: k8s-cluster-1
workers: 3
vsphere:
  # either a cluster or a resource pool
  computeResource: rp1
  datacenter: dc1
  datastore: nfsDatastore
  opsUsername: k8s-cluster-1-opsUsername
  opsPassword: k8s-cluster-1-opsPassword
storageClasses:
- name: silver
  diskformat: thin
  datastore: vsanDatastore
  cacheReservation: 3939
  diskStripes: 3
  forceProvisioning: false
  hostFailuresToTolerate: 3
  iopsLimit: 33393
  objectSpaceReservation: 393939
```
